#include <stdint.h>

uint32_t				load_config_file(const char *);
int					create_config_file(const char *);
void					saveConfig(void);
void					loadConfig(void);

#define SAVECONFIG_MIDIMAP		0x01
#define SAVECONFIG_MOUSEMAP	0x02
#define SAVECONFIG_KEYMAP		0x04
#define SAVECONFIG_DEVICES		0x08
#define SAVECONFIG_OTHER		0x80

#define CONFIGKEY_BYTES		0
#define CONFIGKEY_SHORTS	80
#define CONFIGKEY_LONGS		120
#define CONFIGKEY_ANYSIZE	200

#define CONFIGKEY_BUSS			(CONFIGKEY_BYTES)		// CONFIGKEY_BYTES[0] to CONFIGKEY_BYTES[9]
#define CONFIGKEY_CHAN			(CONFIGKEY_BYTES+10)	// CONFIGKEY_BYTES[10] to CONFIGKEY_BYTES[19]
#define CONFIGKEY_FRAMES		(CONFIGKEY_BYTES+20)
#define CONFIGKEY_MASTERVOL	(CONFIGKEY_BYTES+21)
#define CONFIGKEY_SPLIT			(CONFIGKEY_BYTES+22)
#define CONFIGKEY_CMDSPLIT		(CONFIGKEY_BYTES+23)
#define CONFIGKEY_REVVOL		(CONFIGKEY_BYTES+24)
#define CONFIGKEY_VELCURVE		(CONFIGKEY_BYTES+25)
#define CONFIGKEY_CHORDBOUND	(CONFIGKEY_BYTES+26)
#define CONFIGKEY_TRANSPOSE	(CONFIGKEY_BYTES+27)
#define CONFIGKEY_DCLICKSPEED	(CONFIGKEY_BYTES+28)
#define CONFIGKEY_MASTERCHAN	(CONFIGKEY_BYTES+29)
#define CONFIGKEY_SAMPLERATE	(CONFIGKEY_BYTES+30)
#define CONFIGKEY_BASSOCT		(CONFIGKEY_BYTES+31)
#define CONFIGKEY_SENSITIVITY	(CONFIGKEY_BYTES+32)
#define CONFIGKEY_DRUMTRIGGER	(CONFIGKEY_BYTES+33)

#define CONFIGKEY_DRUMSVOL		(CONFIGKEY_BYTES+40)		// RESERVED TO 44
#define CONFIGKEY_SOLOVOL		(CONFIGKEY_BYTES+44)

#define CONFIGKEY_FLAG			CONFIGKEY_LONGS

// App callbacks
unsigned char *	saveConfigOther(register unsigned char *);
int					loadConfigOther(register unsigned char *, register unsigned long);
extern const char	ConfigDirName[];

